name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create placeholder .env
      uses: canastro/copy-action@0.0.2
      with:
        source: .env.example
        target: .env
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag assistants-bot:$(date +%s)
